/*
    This program copies symbols from .SYM files generated by Aztec C for 68K to CP/M 68K .68K binary files.
    Aztec's linker doesn't write symbols to .68K binary files, hence the need for this program.
    Written by David Lee on January 8, 2026
*/

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <vector>

#include <djl_os.hxx>

#ifndef _WIN32
    #include <unistd.h>
    #include <stdlib.h>
#endif

using namespace std;

bool g_hostIsLittleEndian = true;              // is the host little endian?
bool g_traceStatus = false;

uint32_t swap_endian32( uint32_t x )
{
    if ( g_hostIsLittleEndian )
        return flip_endian32( x );
    return x;
} //swap_endian32

uint16_t swap_endian16( uint16_t x )
{
    if ( g_hostIsLittleEndian )
        return flip_endian16( x );
    return x;
} //swap_endian16

void append_string( char * pc, const char * a )
{
    size_t len = strlen( pc );
    if ( 0 != len )
    {
        pc[ len++ ] = ',';
        pc[ len++ ] = ' ';
    }

    strcpy( pc + len, a );
} //append_string

#pragma pack( push, 1 )

struct HeaderCPM68K    // .68k executable files for cp/m 68k v1.3
{
    uint16_t signature;
    uint32_t cb_text;
    uint32_t cb_data;
    uint32_t cb_bss;
    uint32_t cb_symbols;
    uint32_t reserved;
    uint32_t text_start;
    uint16_t relocation_flag; // two bytes, but only the low byte has the flag

    void swap_endianness()
    {
        signature = swap_endian16( signature );
        cb_text = swap_endian32( cb_text );
        cb_data = swap_endian32( cb_data );
        cb_bss = swap_endian32( cb_bss );
        cb_symbols = swap_endian32( cb_symbols );
        reserved = swap_endian32( reserved );
        text_start = swap_endian32( text_start );
        relocation_flag = swap_endian16( relocation_flag );
    }

    void trace()
    {
        printf( "cpm68k executable header:\n" );
        printf( "  signature: %#x\n", signature );
        printf( "  cb_text: %#x\n", cb_text );
        printf( "  cb_data: %#x\n", cb_data );
        printf( "  cb_bss: %#x\n", cb_bss );
        printf( "  cb_symbols: %#x\n", cb_symbols );
        printf( "  reserved: %#x\n", reserved );
        printf( "  text_start: %#x\n", text_start );
        printf( "  relocation_flag: %#x\n", relocation_flag );
    }
};

struct SymbolEntryCPM
{
    char name[ 8 ];
    uint16_t type;
    uint32_t value;

    void swap_endianness()
    {
        type = swap_endian16( type );
        value = swap_endian32( value );
    }

    const char * get_type()
    {
        static char ac[ 80 ];
        ac[ 0 ] = 0;

        if ( 0x8000 & type )
            append_string( ac, "defined" );
        if ( 0x4000 & type )
            append_string( ac, "equated" );
        if ( 0x2000 & type )
            append_string( ac, "global" );
        if ( 0x1000 & type )
            append_string( ac, "equated-register" );
        if ( 0x800 & type )
            append_string( ac, "external reference" );
        if ( 0x400 & type )
            append_string( ac, "data-based-relocatable" );
        if ( 0x200 & type )
            append_string( ac, "text-based-relocatable" );
        if ( 0x100 & type )
            append_string( ac, "bss-based-relocatable" );

        return ac;
    }

    void trace()
    {
        printf( "  %#16x", value );
        printf( "  %10s", name );
        printf( "  %s\n", get_type() );
    }
};

#pragma pack(pop)

void usage( const char * perr = 0 )
{
    if ( perr )
        printf( "error: %s\n", perr );

    printf( "usage: perr <filename>\n" );
    printf( "      copies symbols from <filename>.SYM to <filename>.68K\n" );
    printf( "  arguments:\n" );
    printf( "      -v verbose output to show status\n" );
    printf( "  background:\n" );
    printf( "      Aztec C 68K creates symbols files using ln68's -T to .SYM files.\n" );
    printf( "      But it doesn't write the symbols to executable .68K files.\n" );
    printf( "      .sym on case-sensitive filesystems must be .sym or .SYM\n" );
    exit( 1 );
} //usage

int main( int argc, char * argv[] )
{
    uint16_t tst = 1;
    g_hostIsLittleEndian = ( 1 & ( * (uint8_t *) &tst ) );

    char * pfilename = 0;

    for ( int arg = 1; arg < argc; arg++ )
    {
        if ( !strcmp( argv[ arg ], "-v" ) )
            g_traceStatus = true;
        else if ( !pfilename )
            pfilename = argv[ arg ];
        else
            usage( "invalid argument" );
    }

    if ( 0 == pfilename )
        usage( "no input file specified" );

    bool use_lower = true;
    char ac[ 255 ];
    strcpy( ac, pfilename );
    strcat( ac, ".sym" );

    FILE * fpInput = fopen( ac, "r" );
    if ( !fpInput )
    {
        strcpy( ac, pfilename );
        strcat( ac, ".SYM" );
        fpInput = fopen( ac, "r" );
        if ( !fpInput )
            usage( "can't open input file" );
        use_lower = false;
    }

    CFile fileInput( fpInput );

    strcpy( ac, pfilename );
    strcat( ac, use_lower ? ".68k" : ".68K" );

    FILE * fpOutput = fopen( ac, "r+b" );
    if ( !fpOutput )
        usage( "can't open output file" );

    CFile fileOutput( fpOutput );

    HeaderCPM68K head;
    size_t read = fread( &head, sizeof( head ), 1, fpOutput );
    if ( 1 != read )
        usage( "can't read header of cp/m 68k image file" );

    head.swap_endianness();

    if ( g_traceStatus )
        head.trace();

    vector<SymbolEntryCPM> cpmSymbols;
    int state = 0; // 1 == text, 2 == data, 3 == bss, 4 == absolute

    while ( fgets( ac, sizeof( ac ), fpInput ) )
    {
        if ( !strncmp( ac, "Segment", 7 ) || !strncmp( ac, "ABSOLUTES", 9 ) )
        {
            state++;
            if ( g_traceStatus )
                printf( "moving to state %d\n", state );
            continue;
        }

        size_t len = strlen( ac );
        if ( len < 11 )
            continue;

        while ( len && ( ac[ len - 1 ] == '\n' ) || ( ac[ len - 1 ] == '\r' ) )
        {
            ac[ len - 1 ] = 0;
            len--;
        }

        SymbolEntryCPM entry;
        char * endptr;
        entry.value = strtoul( ac + 1, &endptr, 16 );
        strncpy( entry.name, ac + 10, 7 );
        entry.name[ 7 ] = 0; // symbols can be 8 characters long with no null termination, but for simplification I use 7 characters with null termination

        // skip over __H? markers because they aren't as useful for debugging and can conflict with actual function names like main()

        if ( !strncmp( entry.name, "__H", 3 ) )
            continue;

        if ( 1 == state )
        {
            entry.type = 0x200;
            entry.value -= head.text_start; // all bases are belong to text
        }
        else if ( 2 == state )
        {
            entry.type = 0x400;
            entry.value -= head.text_start;
        }
        else if ( 3 == state )
        {
            entry.type = 0x100;
            entry.value -= head.text_start;
        }
        else
            entry.type = 0; // absolute

        if ( g_traceStatus )
            entry.trace();

        entry.swap_endianness();

        if ( state <= 3 ) // absolute symbols are just uninteresting stack information; ignore them
            cpmSymbols.push_back( entry );
    }

    if ( g_traceStatus )
        printf( "%zu symbols found\n", cpmSymbols.size() );

    head.cb_symbols = (uint32_t) ( cpmSymbols.size() * sizeof( SymbolEntryCPM ) );
    long symbol_offset = (long) ( sizeof( head) + head.cb_text + head.cb_data );
    fseek( fpOutput, symbol_offset, SEEK_SET );
    size_t written = fwrite( cpmSymbols.data(), cpmSymbols.size() * sizeof( SymbolEntryCPM ), 1, fpOutput );
    if ( -1 == written )
        usage( "failed to write symbols" );

    head.swap_endianness();
    fseek( fpOutput, 0l, SEEK_SET );
    written = fwrite( &head, sizeof( head ), 1, fpOutput );
    if ( -1 == written )
        usage( "failed to update symbol table size in the 68K header" );

    printf( "%zu symbols successfully copied\n", cpmSymbols.size() );
    return 0;
} //main

